all:
	make -f Makefile.mp3test clean
	make -f Makefile.mp3test 
	make -f Makefile.pcmtest clean
	make -f Makefile.pcmtest
	
mp3test:
	make -f Makefile.mp3test clean
	make -f Makefile.mp3test

pcmtest:
	make -f Makefile.pcmtest clean
	make -f Makefile.pcmtest